### ISSUE TITLE
Reimplement in Node

### ISSUE THREAD

**Issue by ronkorving** [gunar/shellcheck#16] opened 2019-05-17 01:44 UTC
I think it fits the target audience to reimplement this package in Node. Since it's being installed via NPM, we know the Node-dependency is covered, but what we don't know is:

- is wget available?
- is curl available?
- is tar available?

There are very adequate pure-JS alternatives for that.

**Comment by gunar** [comment] 2019-05-20 14:37
We could refactor the installation method in JavaScript instead of bash. Good idea @ronkorving

**Comment by jasonkarns** [comment] 2019-08-09 18:26
👍 to this. The only thing to keep in mind is that we won't be able to use npm deps, since npm's behavior around using deps from install scripts is rather undefined. The entire thing would need to be implemented using only the core APIs.

**Comment by ronkorving** [comment] 2019-08-13 01:46
@jasonkarns Could you elaborate? I'm not familiar with this problem.

**Comment by jasonkarns** [comment] 2019-08-13 13:31
this package downloads the shellcheck binary during npm's install process. When a package has dependencies, it is not always certain that those dependencies will be completely installed _prior_ to running the package's pre/post/install hooks. (Recall that npm will de-dupe deps when possible, so some of these deps might be de-duped if required by other packages in the dep tree. Recall also that npm will download many of the deps in the tree in parallel.)

I personally encountered this problem with the cldr-data package, which _also_ downloads assets during its postinstall hook. cldr-data attempted to use the `request` package as a dep from its postinstall script. hence the issue: https://github.com/rxaviers/cldr-data-npm/issues/33

The root cause was npm's inability to guarantee that all package deps are installed _and available_ prior to invoking a package's pre/post/install hooks.

https://github.com/npm/npm/issues/4134
https://github.com/npm/npm/issues/8850
https://github.com/npm/npm/issues/4096
https://github.com/npm/npm/issues/8152

It's possible these bugs with npm are fixed by now. But since we don't _already_ depend on other packages for the download script, I think it would be in our best interests to just implement the install hook with only core node APIs so as to avoid the problem entirely.

**Closed** 2019-11-12 21:27 UTC
Labels: help wanted

**Comment by gunar** [comment] 2019-11-12 21:29
Published as `0.4.0`

**Comment by ronkorving** [comment] 2019-11-13 01:10
You could take it a step further and stream through https://www.npmjs.com/package/tar :)

**Comment by jasonkarns** [comment] 2019-11-13 14:44
@ronkorving it's not stable to use npm deps during an install script: https://github.com/gunar/shellcheck/issues/16#issuecomment-520835526

**Comment by ronkorving** [comment] 2019-11-14 07:21
Oh sorry, I forgot.

**Comment by gunar** [comment] 2019-11-14 22:13
I didn't know there was a tar implementation for node. That's pretty cool. I'd love to do that. Perhaps we can copy and paste the code into this library? Other ideas?

**Comment by ronkorving** [comment] 2019-11-15 05:20
Maybe not a very sexy solution, but it seems that uncompressed binaries are also published: https://storage.googleapis.com/shellcheck/

**Comment by jasonkarns** [comment] 2019-11-15 14:00
It's also possible that npm (and yarn?) have fixed the underlying race conditions that caused the problems above. Though if we added deps, we'd probably have to move the script to `postinstall` instead of `preinstall`, to increase the chances that deps are available when the script runs.
